DEBFLAGS=-g
INCFLAGS = -I./glm-0.9.2.7 -I./mingw_prefix/include -L./mingw_prefix/lib

cube-slime: 	cube-slime.cpp Makefile
		g++ -std=c++0x $(DEBFLAGS) $(INCFLAGS) cube-slime.cpp -o cube-slime -lfreeglut -lglew32 -lopengl32 
clean:
		rm *.o
